title: Blendwalker
description: A collection of guides and resources for making FFXIV-based projects in Blender
theme: just-the-docs
color_scheme: dark

url: https://kajupe.github.io/blendwalker
logo: "/assets/branding/header.webp"
favicon_ico: "/assets/branding/favicon.ico"

aux_links:
  # Template Repository: https://github.com/just-the-docs/just-the-docs-template

search:
    focus_shortcut_key: 'k'

callouts:
  highlight:
    color: blue
  important:
    title: Important
    color: yellow
  new:
    title: New
    color: green
  note:
    title: Note
    color: orchid
  warning:
    title: Warning
    color: lightcoral
